[programs.devnet]
calculator = "DhidfBsE892jsmRzGiQsUBm7QvJN4m9PnC5mJNSAX2EV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/rackham/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
